CONTAINER DaaOceanC4D {
  GROUP DaaOceanC4D_Group {
    DEFAULT 1;
    LONG AAOCEANC4D_RESOLUTION { CUSTOMGUI LONGSLIDER; MIN 1; MAXSLIDER 6; DEFAULT 2; }
    LONG AAOCEANC4D_SPECTRUM { MIN 0; DEFAULT 1;}
    LONG AAOCEANC4D_SEED { MIN 0; DEFAULT 0; }
    REAL AAOCEANC4D_OCEANSCALE { CUSTOMGUI REALSLIDER; MIN 0; MAXSLIDER 1000; DEFAULT 100.0; }
    REAL AAOCEANC4D_OCEANDEPTH { CUSTOMGUI REALSLIDER; MIN 0; MAXSLIDER 100000; DEFAULT 10000.0; }
    REAL AAOCEANC4D_SURFACETENSION { CUSTOMGUI REALSLIDER; MIN 0; MAXSLIDER 5; STEP 0.1; DEFAULT 0.0; }
    REAL AAOCEANC4D_VELOCITY { CUSTOMGUI REALSLIDER; MIN 1; MAXSLIDER 30; DEFAULT 10.0; }
    REAL AAOCEANC4D_CUTOFF { CUSTOMGUI REALSLIDER; MIN 0; MAXSLIDER 20; DEFAULT 0.0; }  // smooth
    REAL AAOCEANC4D_WINDDIRECTION { CUSTOMGUI REALSLIDER; UNIT DEGREE; MINSLIDER 0; MAXSLIDER 360; STEP 1; DEFAULT 0.7853981633974483; }
    LONG AAOCEANC4D_WINDALIGN { CUSTOMGUI LONGSLIDER; MIN 0; MAX 10; DEFAULT 0; }
    REAL AAOCEANC4D_DAMP { CUSTOMGUI REALSLIDER; UNIT PERCENT; MIN 0; MAX 100; STEP 1; DEFAULT 0.3; }
    REAL AAOCEANC4D_WAVESPEED { CUSTOMGUI REALSLIDER; MINSLIDER 0; MAXSLIDER 10; STEP 0.1; DEFAULT 1.0; }
    REAL AAOCEANC4D_WAVEHEIGHT { CUSTOMGUI REALSLIDER; MIN 0.001; MAXSLIDER 100; STEP 0.1; DEFAULT 1.0; }
    REAL AAOCEANC4D_CHOPAMOUNT { CUSTOMGUI REALSLIDER; MINSLIDER 0; MAXSLIDER 6; STEP 0.1; DEFAULT 1.0; }
    REAL AAOCEANC4D_TIME { DEFAULT 0.0; }
    REAL AAOCEANC4D_REPEATTIME { DEFAULT 1000.0; }
    BOOL AAOCEANC4D_FOAM { DEFAULT 0; }
    REAL AAOCEANC4D_RANDWEIGHT { DEFAULT 0.0; }
    REAL AAOCEANC4D_SPECTRUMWEIGHT { CUSTOMGUI REALSLIDER; MIN 1; MAXSLIDER 100; DEFAULT 1.0; }
    REAL AAOCEANC4D_PMWAVESIZE { CUSTOMGUI REALSLIDER; MIN 0.001; MAX 6; STEP 0.1; DEFAULT 1.0;}
    REAL AAOCEANC4D_JSWPFETCH { CUSTOMGUI REALSLIDER; MIN 0.001; MAX 1000; DEFAULT 20.0; }
    REAL AAOCEANC4D_SWELL { CUSTOMGUI REALSLIDER; UNIT PERCENT; MIN 0; MAX 100; STEP 1; DEFAULT 0.0; }
    SEPARATOR { LINE; }
    GROUP {
      STATICTEXT AAOCEANC4D_INFOTEXT { }
    }
  }
}
