CONTAINER OaaOceanDeformer {
  INCLUDE Obase;
  INCLUDE DaaOceanC4D;

  HIDE AAOCEANC4D_FOAM;
  HIDE AAOCEANC4D_RANDWEIGHT;
  HIDE AAOCEANC4D_SPECTRUMWEIGHT;
  HIDE AAOCEANC4D_PMWAVESIZE;
  HIDE AAOCEANC4D_JSWPFETCH;
  HIDE AAOCEANC4D_SWELL;
}
