CONTAINER XaaOceanShader {
  INCLUDE Xbase;
  INCLUDE aaOceanC4D;

  HIDE AAOCEANC4D_RANDWEIGHT;
  HIDE AAOCEANC4D_SPECTRUMWEIGHT;
  HIDE AAOCEANC4D_PMWAVESIZE;
  HIDE AAOCEANC4D_JSWPFETCH;
  HIDE AAOCEANC4D_SWELL;
}
