CONTAINER XaaOceanShader {
  INCLUDE Mpreview;
  INCLUDE Xbase;
  INCLUDE DaaOceanC4D;

  HIDE AAOCEANC4D_RANDWEIGHT;
  HIDE AAOCEANC4D_SPECTRUMWEIGHT;
  HIDE AAOCEANC4D_PMWAVESIZE;
  HIDE AAOCEANC4D_JSWPFETCH;
  HIDE AAOCEANC4D_SWELL;
}
